### ISSUE TITLE
add the possibility to assign own shortcuts for specific website

### ISSUE THREAD

**Issue by der-ali** [Jon-Salmon/hotkey-tabs#1]
it would be really productive to be able to assign personal shortcuts to specific websites instead of hard-coded ones. For example assigning _ctrl+alt+g_ for github. _ctrl+alt+c_ for cnn and so on.
Before FF57 there was an an extension named [sitelaucher](https://addons.mozilla.org/en-US/firefox/addon/sitelauncher/?src=userprofile) for this aim but it's not more available.

**Comment by Jon-Salmon** [comment]
Unfortuanly, due to some limitations with the current firefox addon system, it isn't currently possible to achive this efficiently.

Mozilla are planning on alowing shortcuts to be changed (see [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) here), which is planned for release with FF60. I'll do my best to support this feature once the FF60 beta is released in a few weeks.

**Comment by Jon-Salmon** [comment]
I've just released version 1.8 of this addon which addes support for changing the default shortcuts. Once your running FF60 or above (should be released sometime mid May), the options will apear in the addon's settings page.
